apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-quarkus-app-native
  description: A cool quarkus app
  annotations:
    argocd/app-name: my-quarkus-app-native-bootstrap
    backstage.io/kubernetes-id: my-quarkus-app-native
    # It must be commented otherwise we cannot see the Tekton pipelines resources
    # backstage.io/kubernetes-namespace: cmoullia
    backstage.io/source-location: url:https://github.com/ch007m/my-quarkus-app-native
    # The janus-idp.io/tekton allows to set the boolean value: isTektonCIAvailable which is used within the UI to enable/disable the TektonCIComponent
    janus-idp.io/tekton: my-quarkus-app-native
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ch007m/
    # See: topology annotation: https://github.com/janus-idp/backstage-plugins/tree/main/plugins/topology
    app.kubernetes.io/name: quarkus
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
